### ISSUE TITLE
fix windows build action

### ISSUE THREAD

**Issue by zkrige** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#107]
Currently windows is failing with this error:
build-win
There is not enough space on the disk. : 'D:\a\_temp\_runner_file_commands\set_env_38fd79c1-588f-4f95-818f-1979f1963142'

I'll investigate how to add more disk space

**Comment by zkrige** [comment]
perhaps we can remove some of the installed software as one of the build steps? maybe this will free enough space

**Comment by zkrige** [comment]
or we can build a docker image with windows in it and self host the runner

**Comment by iteufel** [comment]
To save space we can add packages we don't need for the build to the [custom_deps](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/blob/89a16332515a16187683de72375a819e52d35c88/build.js#L115).

**Comment by zkrige** [comment]
I'm not too familiar with the actual nwjs ffmpeg build process - you'd know more about that. I assume that the chrome build is what's taking up all the space?

**Comment by iteufel** [comment]
Currently all dependencies for the whole chromium project are loaded.

I had already built it in the past so that only dependencies of FFmpeg were loaded.
But this was very error prone and had to be adjusted almost every chromium release.

I'll see if it's enough to remove some big dependencies that are not needed.

**Comment by zkrige** [comment]
I'm guessing the linux and Mac builds will also fail due to size. hopefully if you can strip out some big dependencies then we should be good to go

**Comment by zkrige** [comment]
@iteufel have you had any progress in removing some of the dependencies? Alternatively, perhaps we an spin up our own windows image?
