### ISSUE TITLE
Chromium 94 introduces a new required symbol av_stream_get_first_dts

### ISSUE THREAD

**Issue by barsnick** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#117]
Short version: We need a new build. ;)

Chromium 94, which has just recently been promoted from the Dev to the Beta channel, seems to have introduced a new symbol, which the most recent build of this project does not yet provide. (Actually, I have been using a quite old version of nwjs-ffmpeg-prebuilt for Linux for quite a long time, successfully, despite updates to most recent Chromium on Opera - until now).

The missing symbol is av_stream_get_first_dts, and Opera Developer 80.0.4157.0 (using Chrome/94.0.4603.0) therefore refuses to launch with this library.

The use of the symbol was introduced here:
https://github.com/chromium/chromium/commit/b94755e4633045be96ab5e0bdde0db7e16a804bd

Here is one commit referencing the symbol in chromium ffmpeg source:
https://chromium.googlesource.com/chromium/third_party/ffmpeg/+/1f33e234be4e2823c663d02b3baa3e7a7cfc33cb

Thanks for the valuable builds!

**Comment by zmike** [comment]
Confirmed, newer versions of chromium don't work with the latest (0.55) release.

**Comment by LorenDB** [comment]
Can we please have a newer build? I'm really wishing for this to be resolved.

**Comment by bulvara** [comment]
https://github.com/archlinux/svntogit-packages/blob/packages/qt5-webengine/trunk/qt5-webengine-ffmpeg5.patch was fixing av_stream_get_first_dts for ffmpeg 5.0, but fails with current git master
