### ISSUE TITLE
Opera Stable 79.0.4143.22 crashes on playing videos

### ISSUE THREAD

**Issue by danielbgto** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#119]
Just came opera  79.0.4143.22 stable release and tab trying to play video is crashing. There is segfault in dmesg regarding that.
Example: Media[116803]: segfault at 6400000028 ip 00007f5089ab3a90 sp 00007f507d0d1c80 error 4 in libffmpeg.so[7f5089914000+2fb000]
Thank you for that tremendous work!

**Comment by flopezre** [comment]
Confirmed:
<img src="https://freeimage.host/i/screenshot-2021-09-14-15-30-49.RgOeQ2" width="400"/>

**Comment by choyan** [comment]
Same here.

**Comment by danielbgto** [comment]
I found a workaround. Install latest Vivaldi browser 4.2 and the take the lib:
sudo cp /var/opt/vivaldi/media-codecs-79b56700ea9558c50a5edacaeb70298120127d2f8b32bb5e05c3876a51bd64b5/libffmpeg.so /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so

**Comment by choyan** [comment]
Another work around. 
- Download the latest Vivaldi `ffmpeg` from here [Vivaldi Archlinux Archive](https://archlinux.org/packages/community/x86_64/vivaldi-ffmpeg-codecs/) . It comes with a zip file with named `vivaldi-ffmpeg-codecs-93.0.4577.82-1-x86_64.pkg.tar.zst` . 
- Inside the `opt/vivaldi` foder you will find you will find `libffmpeg.so.4.2`. Extract it and rename it to `libffmpeg.so`
- Copy the file file to `/usr/lib/x86_64-linux-gnu/opera` folder

**Comment by jkucinski** [comment]
Don't work on CentOS 8 with glibc version 2.28. Vivaldi Archlinux Archive require glibc version 2.29.

**Comment by caioz7** [comment]
> Another work around. (Tested on Ubuntu 20.04)
> 
> * Download the latest Vivaldi `ffmpeg` from here [Vivaldi Archlinux Archive](https://archlinux.org/packages/community/x86_64/vivaldi-ffmpeg-codecs/) . It comes with a zip file with named `vivaldi-ffmpeg-codecs-93.0.4577.82-1-x86_64.pkg.tar.zst` .
> * Inside the `opt/vivaldi` foder you will find you will find `libffmpeg.so.4.2`. Extract it and rename it to `libffmpeg.so`
> * Copy the file file to `/usr/lib/x86_64-linux-gnu/opera` folder

works for me, Opera: 79.0.4143.22 - Kubuntu 21.04

**Comment by Ld-Hagen** [comment]
https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine

**Comment by barsnick** [comment]
What about Opera Developer >= 80.0.4157.0?
See #117.

**Comment by Ld-Hagen** [comment]
> What about Opera Developer >= 80.0.4157.0?

Try this https://repo.herecura.eu/herecura/x86_64/opera-developer-ffmpeg-codecs-95.0.4621.4-1-x86_64.pkg.tar.zst

**Comment by connectnet** [comment]
[https://archlinux.org/packages/community/x86_64/vivaldi-ffmpeg-codecs/download](url)
Inside the opt/vivaldi foder you will find you will find libffmpeg.so.4.2. Extract it and rename it to libffmpeg.so

**Comment by luksak** [comment]
The vivaldi binary works for me as well.
