### ISSUE TITLE
Opera failed to open after copying the release file into its lib folder

### ISSUE THREAD

**Issue by lavanyadeepak** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#124]
I had a problem with Opera to play videos and had copied the same to its lib folder. But after that it stopped opening itself. Hence had to restore the old. Please see my terminal output. The .new is the one which I downloaded from release folder.

![image](https://user-images.githubusercontent.com/2217926/141020640-70695372-2157-4e5f-b0ad-1cb5eb0718a7.png)

**Comment by Ld-Hagen** [comment]
It's too old. Build new one, or use https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine
