### ISSUE TITLE
no version for 0.57.1, what can i use?

### ISSUE THREAD

**Issue by ostwindli** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#136]

**Comment by ostwindli** [comment]
@zkrige why closed?

**Comment by zkrige** [comment]
I can't build for older versions of nwjs. If possible can you upgrade to a newer nwjs and use one of the builds here

**Comment by ostwindli** [comment]
Fine, I will try to upgrade nwjs soon.
But, before this,  can you tell me how to build a ffmpeg version ?

**Comment by ostwindli** [comment]
get. thks
