### ISSUE TITLE
Request to move repo under NW Userland

### ISSUE THREAD

**Issue by ayushmxn** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#139]
Hi @zkrige,

I've recently created a GitHub org called [NW Userland](https://github.com/nw-userland) which is my attempt to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things. Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by zkrige** [comment]
I don't think we can move it there. There are a lot of third party dependencies that depend on this specific GitHub url. Also, I'm not really the owner - @iteufel is the owner. I'm just maintaining as he is quite busy and unable to maintain currently

**Comment by ayushmxn** [comment]
Ah ok, good to know!
