### ISSUE TITLE
No more releases for Linux ia32?

### ISSUE THREAD

**Issue by Yaguar666** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#142]
Hi!
I tried release 0.68.1 for Linux ia32, but NW doesn't start...

Found that ./libffmpeg.so was build for x86-64

@debian:~$ readelf -h ./libffmpeg.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          18208680 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         38
  Section header string table index: 36

Can you rebuild this lib for x86?

**Comment by Yaguar666** [comment]
up

**Comment by oech3** [comment]
Worked. Please wait merging of `make` build.
