### ISSUE TITLE
I need help upgrading GitHub actions

### ISSUE THREAD

**Issue by zkrige** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#144]
our build is giving the following warning

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-node, actions/checkout, actions/upload-artifact, actions/checkoutShow more`

is there anyone in this community who would be willing to help upgrade this

**Comment by tharatau** [comment]
I can give this a shot.

**Comment by zkrige** [comment]
That would be fantastic. What do you need from me

**Comment by tharatau** [comment]
> What do you need from me

Nothing I think. I have an [action](https://github.com/tharatau/nwjs-ffmpeg-prebuilt/actions/runs/3922510251) running on my fork currently. Not sure how long it's supposed to take. I'll open a PR right after it succeeds.

**Comment by zkrige** [comment]
@tharatau I see your action has a bunch of deprecation warnings - the same as ours

**Comment by tharatau** [comment]
I updated the action versions in another branch. I think creating a release defaulted to the master branch on my fork.

**Comment by zkrige** [comment]
@tharatau gosh that is weird. the Mac resource was created. im not sure why the action can't access it

**Comment by tharatau** [comment]
https://github.com/tharatau/nwjs-ffmpeg-prebuilt/blob/494fa1ba298dfe0b1a26906bd58c47b64fe3eb0b/.github/workflows/main.yml#L120
I must have missed this. I guess I need to create GITHUB_TOKEN

**Comment by zkrige** [comment]
great - let me know when you're ready to do a pull request

**Comment by tharatau** [comment]
I'm getting a `socket hang up` error with the [release action](https://github.com/svenstaro/upload-release-action/issues/44). I'll try using a different action for it.``

**Comment by zkrige** [comment]
Let me know if there's anything I can do to help

Curious why it happens on your repo but not mine

**Comment by tharatau** [comment]
Might be related to GitHub API. If it still happens on this PR, then it's probably related to the upload action. My plan is to create a pr-release via the PR.

**Comment by tharatau** [comment]
Forgot to reference this. Can be closed for now.

**Comment by zkrige** [comment]
@tharatau looks like it worked

thanks for your help
