### ISSUE TITLE
[Feature Request] Auto build/release on NW.js version bump

### ISSUE THREAD

**Issue by tharatau** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#156]
## Description

If NW manifest latest version is greater than latest ffmpeg version, build and release ffmpeg for NW latest version.

Maybe we could have a job which checks once a day?

**Comment by zkrige** [comment]
@tharatau would you know how to this? If you can help out here, that would be amazing

**Comment by tharatau** [comment]
I can give this a shot!

**Comment by zkrige** [comment]
I _think_ something like this might be helpful - https://stackoverflow.com/a/68407424/541634

**Comment by tharatau** [comment]
Could you assign me to this issue? That way I don't lose track of it.

**Comment by zkrige** [comment]
thank you!

**Comment by zkrige** [comment]
@tharatau did you ever manage to make any progress on this?

**Comment by tharatau** [comment]
I haven't gotten around to it yet - been busy with exams! Looked into it and should not be hard to implement. Will probably open a PR by end of this week.

**Comment by tharatau** [comment]
Made some progress. I have a cron job to check the latest version. I now have to figure out how to trigger the build job if the version is not latest.

**Comment by tharatau** [comment]
@zkrige This should be ready for review. It checks for latest version and [fails if it is up to date](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/pull/159). Manually creating a release [triggers the build](https://github.com/tharatau/nwjs-ffmpeg-prebuilt/actions/runs/4917970141).

**Comment by zkrige** [comment]
@tharatau I see the build runs EVERY night, even if there isn't a new version available

**Comment by tharatau** [comment]
@zkrige Hmmm, I'm not sure what's going on. I think we could comment out the daily check stuff for now? I can look into it when I have more time.

**Comment by zkrige** [comment]
its weird because the "is_latest" workflow exited correctly (exited with status 1) which means it shouldn't have triggered the daily action

**Comment by zkrige** [comment]
oh I thin I see the problem. the "CI" workflow is set to run "daily"

**Comment by tharatau** [comment]
https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/blob/d0f688f43ac24c04274810efd9e0512d5b37b11c/.github/workflows/main.yml#L18
Might have to do with syntax of second condition? YAML files are unnecessarily mysterious.

**Comment by tharatau** [comment]
Daily just references the `daily.yml` file. The job `is-latest` is the thing that runs daily.

**Comment by zkrige** [comment]
can I merge is-latest into daily.yaml? that way we dont need to depend on workflow result - we can just check output of script directly in that file

**Comment by zkrige** [comment]
@tharatau I've merged it into a single yaml file - will you have a look and see if I've missed anyhing
