### ISSUE TITLE
Add support for ARM builds

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#164]
Refs: https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/pull/162#issuecomment-1551444984

**Comment by zkrige** [comment]
relevant NWJS thread - https://github.com/nwjs/nw.js/issues/7620#issuecomment-1550950751

**Comment by ayushmanchhabra** [comment]
@zkrige 👋🏼 

https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/blob/682db480e0d469fbe0f344ffa31b507594b9631c/.github/workflows/main.yml#L14
I think the reason CI is failing is because the repo is not being checked out in the `is_latest` job.

https://github.com/nwjs/nw.js/issues/7620#issuecomment-1549934534
ARM builds are scheduled to be released with 0.77 in June. I'll get started on a PR within the next 2 days.

**Comment by zkrige** [comment]
thanks @ayushmanchhabra 

technically the "is-latest" check is meant to fail when there is no new version. so currently it is working as expected

I'd be happy to assign the arm issue to you :)

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/actions/runs/5127557104/jobs/9223323178
@zkrige The error says no such file or directory found - which made me think its probably because the repo hasn't been checked out for that job.

**Comment by zkrige** [comment]
hmmm yeh - you're right. I've updated and added the checkout step. lets see how it goes

**Comment by zkrige** [comment]
@ayushmanchhabra the action seems better now

**Comment by ayushmanchhabra** [comment]
The main question to get this working is - is it possible to build MacOS ARM executable on MacOS AMD? GitHub Actions only supports AMD for now.

**Comment by zkrige** [comment]
I see they're looking at doing arm runners later this year

https://github.com/github/roadmap/issues/528

**Comment by zkrige** [comment]
@ayushmanchhabra good work!

let me know when PR is ready to merge

**Comment by ayushmanchhabra** [comment]
ready now!

**Comment by TongDaDa** [comment]
@zkrige  Hello, could you provide an arm64 & 0.78.1 nwjs ffmpeg release?

**Comment by ayushmanchhabra** [comment]
@TongDaDa release is available now!

**Comment by zkrige** [comment]
@TongDaDa you'll be the first person to test these arm64 builds, so I'd love to hear your feedback

**Comment by TongDaDa** [comment]
> @TongDaDa you'll be the first person to test these arm64 builds, so I'd love to hear your feedback

It seems not being lucky, the  arm64 assembled in nwjs(0.78.1) performed HIGH cpu rate while playing MP4 video.
