### ISSUE TITLE
Latest nwjs build is building as master instead of <version>

### ISSUE THREAD

**Issue by zkrige** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#166]
I'm not sure how to bring the version tag across in the build files. The result is that I have to manually rename the release from `master` to <version> (eg `0.77.0`)

**Comment by ayushmanchhabra** [comment]
@zkrige Noticed that you got this working! I was banging my head against the wall trying to get the env variable stuff to work.

**Comment by zkrige** [comment]
@ayushmanchhabra well im not sure if its working yet :)

I think it should be tho

**Comment by zkrige** [comment]
ok _now_ it should work
