### ISSUE TITLE
Add support for more codecs

### ISSUE THREAD

**Issue by zkrige** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#170]
### Discussed in https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **artem-alexandrov** April 24, 2023</sup>
Does it support h265? One of users claim that it doesn't, is it possible to add h265 support to the lib?</div>

Ideally we want to add support for as many codecs as possible

I see there is this flag `enable_ffmpeg_video_decoders=true` which isn't used at the moment. This should be investigated

**Comment by Ld-Hagen** [comment]
Probably you need to add gen flags
`enable_platform_hevc = true enable_hevc_parser_and_hw_decoder = true`
