### ISSUE TITLE
Opera 110.0.5130.49 will not play certain proprietary (DRM) content (YouTube, ...) using this `nwjs-ffmpeg-prebuilt` on Linux

### ISSUE THREAD

**Issue by MartinVonReichenberg** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#184]
Hello,
`opera-stable_110.0.5130.49_amd64.rpm` will not play certain YouTube videos after copying  `libffmpeg.so` extracted from `nwjs-ffmpeg-prebuilt/0.88.0-linux-x64.zip` inserted into `/usr/lib64/opera/lib_extra/` on **SUSE Linux**.

You can try it on your own using [this video](https://youtu.be/wvF00KhojsM?si=0nVHf3BOyHJoDPdy), for example.

The only way which works is using the bundled **FFmpeg** inside **Chromium SOURCE** getting the [opera-ffmpeg-codecs](https://aur.archlinux.org/packages/opera-ffmpeg-codecs)  or  [opera-ffmpeg-codecs-bin](https://aur.archlinux.org/packages/opera-ffmpeg-codecs-bin) from AUR.

_You can also take a look at the screenshot of my desktop:_

![Screenshot_20240530_182317](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/assets/110736521/76538b50-98e3-4acc-a83e-c1e1c1c05d4f)

_Thank you for acknowledging the issue . . .
Good luck!_

**Comment by Ld-Hagen** [comment]
For Opera 110 use ffmpeg 0.87

**Comment by MartinVonReichenberg** [comment]
> For Opera 110 use ffmpeg 0.87


Ahhh,

Not mentioned anywhere . . .

**Comment by zkrige** [comment]
Hmmmm. Does anyone perhaps have any idea why this isn't working? I don't think anything has changed in the build process.

**Comment by MartinVonReichenberg** [comment]
> Hmmmm. Does anyone perhaps have any idea why this isn't working? I don't think anything has changed in the build process. 
> 
> 

From what I noticed, Opera lags behind the very latest stable upstream Chromium builds, it is usually one version older _(old-stable)_ than Google Chrome/Chromium that means the bundled **FFmpeg** codec needs to be derived (needs to match) the same version as the latest stable Opera release.

Are these builds on par as follows:
88 - Chromium version **125**.xxx.xx...
87 - Chromium version **124**.xxx.xx...
86 - Chromium version **123**.xxx.xx
Etc . . . 
?_?

If so, certain changes within information mentioned here need to be adjusted for convenience and compliance.

**Comment by MartinVonReichenberg** [comment]
> Hmmmm. Does anyone perhaps have any idea why this isn't working? I don't think anything has changed in the build process. 
> 
> 

From what I noticed, Opera lags behind the very latest stable upstream Chromium builds, it is usually one version older _(old-stable)_ than Google Chrome/Chromium that means the bundled **FFmpeg** codec needs to be derived (needs to match) the same version as the latest stable Opera release.

Are these builds on par as follows:
88 - Chromium version **125**.xxx.xx...
87 - Chromium version **124**.xxx.xx...
86 - Chromium version **123**.xxx.xx
Etc . . . 
?_?

If so, certain changes within information mentioned here need to be adjusted for convenience and compliance.

**Comment by jameskentTX** [comment]
@MartinVonReichenberg

My Opera (debian 12) crashed when I tried to use newest 0.88 codec with Chromium 124. 0.87 codec is working fine.

**Comment by MartinVonReichenberg** [comment]
> @MartinVonReichenberg
> 
> My Opera (debian 12) crashed when I tried to use newest 0.88 codec with Chromium 124. 0.87 codec is working fine.

That is due to Opera (stable) being built on Chromium 124.x.xx. ....
`libffmpeg.so` requires the same Chromium version for some reason...

**Comment by MartinVonReichenberg** [comment]
So the **SOLUTION** is:
If **Opera** is based on **Chromium** version: `126.x.xxxx.xxx` _(`126.0.6478.183`)_ then an appropriate **version** of `nwjs-ffmpeg-prebuilt` needs to be used according to https://nwjs.io/versions.json:

```
{
    "latest": "v0.89.0",
    "stable": "v0.89.0",
    "lts": "v0.14.7",
    "versions": [
        {
            "version": "v0.89.0",
            "date": "2024/06/25",
            "files": ["win-x64", "win-ia32", "linux-x64", "linux-ia32", "osx-x64", "osx-arm64"],
            "flavors": ["normal", "sdk"],
            "components": {
                "node": "22.2.0",
                "chromium": "126.0.6478.57"
            }
        },
```

So **version** `0.89.0` = `126.x.xxxx.xxx`

More information about [CHROMIUM RELEASES](https://chromiumdash.appspot.com/releases?platform=Linux)
