### ISSUE TITLE
about old version use arm64 libffmpeg.dylib

### ISSUE THREAD

**Issue by foolzhang** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#194]
i see this repo start surpport arm64 from [0.78.1](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/tag/0.78.1), is there any way to support old verstion like [0.55.0](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/tag/0.55.0), or old verstion libffmpeg.dylib has suported arm64 ,so we can use directly and don't need to fit it.

background: we hava no plane to upgrade nw.js version. and one more thing whether have wiki to teach me  how to build arm64 libffmpeg.dylib in old version like 0.55.0 to adapter nw.js 0.55.0

**Comment by zkrige** [comment]
I modified the build pipeline to run for older versions, but the build fails.

Im not even sure if 0.55.0 supports arm?

**Comment by foolzhang** [comment]
nw.js has a version [0.57.1](https://github.com/nwjs/nw.js/releases/tag/nw-v0.57.1), i can't find target libffmpeg.dylib in releases, can you help me build one, thanks

one more things, Here is some one unofficial prebuilt [0.57.1 for arm](https://github.com/corwin-of-amber/nw.js/releases/tag/nw-v0.57.1%2BM1), is it posible to build one more libffmpeg.dylib for arm64?

**Comment by foolzhang** [comment]
@zkrige I was hoping you could help me

**Comment by zkrige** [comment]
Unfortunately we are not able to build older versions - I tried recently and it failed with a bunch of errors
